// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: behavior.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdaptationLog = `-- name: CreateAdaptationLog :one

INSERT INTO adaptation_logs (user_id, adaptation_reason, difficulty_change, previous_difficulty, new_difficulty, trigger_metrics)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, adaptation_reason, difficulty_change, previous_difficulty, new_difficulty, trigger_metrics, created_at
`

type CreateAdaptationLogParams struct {
	UserID             pgtype.UUID    `json:"user_id"`
	AdaptationReason   string         `json:"adaptation_reason"`
	DifficultyChange   pgtype.Numeric `json:"difficulty_change"`
	PreviousDifficulty pgtype.Numeric `json:"previous_difficulty"`
	NewDifficulty      pgtype.Numeric `json:"new_difficulty"`
	TriggerMetrics     []byte         `json:"trigger_metrics"`
}

// Adaptation Logs
func (q *Queries) CreateAdaptationLog(ctx context.Context, arg CreateAdaptationLogParams) (AdaptationLog, error) {
	row := q.db.QueryRow(ctx, createAdaptationLog,
		arg.UserID,
		arg.AdaptationReason,
		arg.DifficultyChange,
		arg.PreviousDifficulty,
		arg.NewDifficulty,
		arg.TriggerMetrics,
	)
	var i AdaptationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdaptationReason,
		&i.DifficultyChange,
		&i.PreviousDifficulty,
		&i.NewDifficulty,
		&i.TriggerMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const createBehaviorProfile = `-- name: CreateBehaviorProfile :one

INSERT INTO behavior_profiles (user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed, delivery_mode, emotional_state, ai_profile_summary)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed, created_at, updated_at, last_notified_at, delivery_mode, emotional_state, ai_profile_summary
`

type CreateBehaviorProfileParams struct {
	UserID              pgtype.UUID    `json:"user_id"`
	Goals               []byte         `json:"goals"`
	Constraints         []byte         `json:"constraints"`
	PsychologicalState  []byte         `json:"psychological_state"`
	DifficultyLevel     pgtype.Numeric `json:"difficulty_level"`
	OnboardingCompleted bool           `json:"onboarding_completed"`
	DeliveryMode        string         `json:"delivery_mode"`
	EmotionalState      string         `json:"emotional_state"`
	AiProfileSummary    []byte         `json:"ai_profile_summary"`
}

// Behavior Profiles
func (q *Queries) CreateBehaviorProfile(ctx context.Context, arg CreateBehaviorProfileParams) (BehaviorProfile, error) {
	row := q.db.QueryRow(ctx, createBehaviorProfile,
		arg.UserID,
		arg.Goals,
		arg.Constraints,
		arg.PsychologicalState,
		arg.DifficultyLevel,
		arg.OnboardingCompleted,
		arg.DeliveryMode,
		arg.EmotionalState,
		arg.AiProfileSummary,
	)
	var i BehaviorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goals,
		&i.Constraints,
		&i.PsychologicalState,
		&i.DifficultyLevel,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastNotifiedAt,
		&i.DeliveryMode,
		&i.EmotionalState,
		&i.AiProfileSummary,
	)
	return i, err
}

const createDailyPlan = `-- name: CreateDailyPlan :one

INSERT INTO daily_plans (user_id, plan_date, difficulty_score, status, prompt_version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, plan_date, difficulty_score, status, created_at, updated_at, prompt_version
`

type CreateDailyPlanParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	PlanDate        pgtype.Date    `json:"plan_date"`
	DifficultyScore pgtype.Numeric `json:"difficulty_score"`
	Status          string         `json:"status"`
	PromptVersion   string         `json:"prompt_version"`
}

// Daily Plans
func (q *Queries) CreateDailyPlan(ctx context.Context, arg CreateDailyPlanParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, createDailyPlan,
		arg.UserID,
		arg.PlanDate,
		arg.DifficultyScore,
		arg.Status,
		arg.PromptVersion,
	)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptVersion,
	)
	return i, err
}

const createPlanTask = `-- name: CreatePlanTask :one

INSERT INTO plan_tasks (daily_plan_id, title, description, category, difficulty, position, task_type, suggested_time, anchor_label)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, daily_plan_id, title, description, category, difficulty, position, created_at, task_type, suggested_time, anchor_label
`

type CreatePlanTaskParams struct {
	DailyPlanID   pgtype.UUID    `json:"daily_plan_id"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	Category      string         `json:"category"`
	Difficulty    pgtype.Numeric `json:"difficulty"`
	Position      int32          `json:"position"`
	TaskType      string         `json:"task_type"`
	SuggestedTime string         `json:"suggested_time"`
	AnchorLabel   string         `json:"anchor_label"`
}

// Plan Tasks
func (q *Queries) CreatePlanTask(ctx context.Context, arg CreatePlanTaskParams) (PlanTask, error) {
	row := q.db.QueryRow(ctx, createPlanTask,
		arg.DailyPlanID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Difficulty,
		arg.Position,
		arg.TaskType,
		arg.SuggestedTime,
		arg.AnchorLabel,
	)
	var i PlanTask
	err := row.Scan(
		&i.ID,
		&i.DailyPlanID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.Position,
		&i.CreatedAt,
		&i.TaskType,
		&i.SuggestedTime,
		&i.AnchorLabel,
	)
	return i, err
}

const deleteBehaviorProfile = `-- name: DeleteBehaviorProfile :exec
DELETE FROM behavior_profiles WHERE user_id = $1
`

func (q *Queries) DeleteBehaviorProfile(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBehaviorProfile, userID)
	return err
}

const expireOldPlans = `-- name: ExpireOldPlans :execrows

UPDATE daily_plans SET status = 'expired'
WHERE plan_date < CURRENT_DATE AND status NOT IN ('expired', 'completed')
`

// Scheduled Jobs
func (q *Queries) ExpireOldPlans(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireOldPlans)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveDailyPlan = `-- name: GetActiveDailyPlan :one
SELECT id, user_id, plan_date, difficulty_score, status, created_at, updated_at, prompt_version FROM daily_plans
WHERE user_id = $1 AND plan_date = CURRENT_DATE AND status != 'expired'
`

func (q *Queries) GetActiveDailyPlan(ctx context.Context, userID pgtype.UUID) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, getActiveDailyPlan, userID)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptVersion,
	)
	return i, err
}

const getAdaptationLogsByUser = `-- name: GetAdaptationLogsByUser :many
SELECT id, user_id, adaptation_reason, difficulty_change, previous_difficulty, new_difficulty, trigger_metrics, created_at FROM adaptation_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetAdaptationLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetAdaptationLogsByUser(ctx context.Context, arg GetAdaptationLogsByUserParams) ([]AdaptationLog, error) {
	rows, err := q.db.Query(ctx, getAdaptationLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdaptationLog{}
	for rows.Next() {
		var i AdaptationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AdaptationReason,
			&i.DifficultyChange,
			&i.PreviousDifficulty,
			&i.NewDifficulty,
			&i.TriggerMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdherenceStateByUserID = `-- name: GetAdherenceStateByUserID :one
SELECT id, user_id, completion_rate, streak_count, total_tasks, completed_tasks, difficulty_mismatch, last_computed_at, created_at, updated_at FROM adherence_states WHERE user_id = $1
`

func (q *Queries) GetAdherenceStateByUserID(ctx context.Context, userID pgtype.UUID) (AdherenceState, error) {
	row := q.db.QueryRow(ctx, getAdherenceStateByUserID, userID)
	var i AdherenceState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompletionRate,
		&i.StreakCount,
		&i.TotalTasks,
		&i.CompletedTasks,
		&i.DifficultyMismatch,
		&i.LastComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBehaviorProfileByUserID = `-- name: GetBehaviorProfileByUserID :one
SELECT id, user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed, created_at, updated_at, last_notified_at, delivery_mode, emotional_state, ai_profile_summary FROM behavior_profiles WHERE user_id = $1
`

func (q *Queries) GetBehaviorProfileByUserID(ctx context.Context, userID pgtype.UUID) (BehaviorProfile, error) {
	row := q.db.QueryRow(ctx, getBehaviorProfileByUserID, userID)
	var i BehaviorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goals,
		&i.Constraints,
		&i.PsychologicalState,
		&i.DifficultyLevel,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastNotifiedAt,
		&i.DeliveryMode,
		&i.EmotionalState,
		&i.AiProfileSummary,
	)
	return i, err
}

const getCategoryPerformance = `-- name: GetCategoryPerformance :many
SELECT pt.category,
       COUNT(pt.id)::int AS total_tasks,
       COUNT(el.id) FILTER (WHERE el.completed = TRUE)::int AS completed_tasks
FROM plan_tasks pt
JOIN daily_plans dp ON dp.id = pt.daily_plan_id
LEFT JOIN execution_logs el ON el.plan_task_id = pt.id AND el.completed = TRUE
WHERE dp.user_id = $1 AND dp.plan_date >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY pt.category
ORDER BY pt.category
`

type GetCategoryPerformanceRow struct {
	Category       string `json:"category"`
	TotalTasks     int32  `json:"total_tasks"`
	CompletedTasks int32  `json:"completed_tasks"`
}

func (q *Queries) GetCategoryPerformance(ctx context.Context, userID pgtype.UUID) ([]GetCategoryPerformanceRow, error) {
	rows, err := q.db.Query(ctx, getCategoryPerformance, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryPerformanceRow{}
	for rows.Next() {
		var i GetCategoryPerformanceRow
		if err := rows.Scan(&i.Category, &i.TotalTasks, &i.CompletedTasks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyCompletionRates = `-- name: GetDailyCompletionRates :many

SELECT dp.plan_date,
       COUNT(pt.id)::int AS total_tasks,
       COUNT(el.id) FILTER (WHERE el.completed = TRUE)::int AS completed_tasks
FROM daily_plans dp
JOIN plan_tasks pt ON pt.daily_plan_id = dp.id
LEFT JOIN execution_logs el ON el.plan_task_id = pt.id AND el.completed = TRUE
WHERE dp.user_id = $1 AND dp.plan_date <= CURRENT_DATE
GROUP BY dp.plan_date
ORDER BY dp.plan_date DESC
LIMIT $2
`

type GetDailyCompletionRatesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type GetDailyCompletionRatesRow struct {
	PlanDate       pgtype.Date `json:"plan_date"`
	TotalTasks     int32       `json:"total_tasks"`
	CompletedTasks int32       `json:"completed_tasks"`
}

// Analytics Queries
// Replaces N+1 streak computation (60+ queries → 1)
func (q *Queries) GetDailyCompletionRates(ctx context.Context, arg GetDailyCompletionRatesParams) ([]GetDailyCompletionRatesRow, error) {
	rows, err := q.db.Query(ctx, getDailyCompletionRates, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyCompletionRatesRow{}
	for rows.Next() {
		var i GetDailyCompletionRatesRow
		if err := rows.Scan(&i.PlanDate, &i.TotalTasks, &i.CompletedTasks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyPlanByUserAndDate = `-- name: GetDailyPlanByUserAndDate :one
SELECT id, user_id, plan_date, difficulty_score, status, created_at, updated_at, prompt_version FROM daily_plans WHERE user_id = $1 AND plan_date = $2
`

type GetDailyPlanByUserAndDateParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PlanDate pgtype.Date `json:"plan_date"`
}

func (q *Queries) GetDailyPlanByUserAndDate(ctx context.Context, arg GetDailyPlanByUserAndDateParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, getDailyPlanByUserAndDate, arg.UserID, arg.PlanDate)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptVersion,
	)
	return i, err
}

const getDifficultyTrajectory = `-- name: GetDifficultyTrajectory :many
SELECT dp.plan_date, dp.difficulty_score
FROM daily_plans dp
WHERE dp.user_id = $1 AND dp.plan_date >= CURRENT_DATE - INTERVAL '30 days'
ORDER BY dp.plan_date
`

type GetDifficultyTrajectoryRow struct {
	PlanDate        pgtype.Date    `json:"plan_date"`
	DifficultyScore pgtype.Numeric `json:"difficulty_score"`
}

func (q *Queries) GetDifficultyTrajectory(ctx context.Context, userID pgtype.UUID) ([]GetDifficultyTrajectoryRow, error) {
	rows, err := q.db.Query(ctx, getDifficultyTrajectory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDifficultyTrajectoryRow{}
	for rows.Next() {
		var i GetDifficultyTrajectoryRow
		if err := rows.Scan(&i.PlanDate, &i.DifficultyScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionLogsByDailyPlan = `-- name: GetExecutionLogsByDailyPlan :many
SELECT el.id, el.plan_task_id, el.user_id, el.completed, el.completed_at, el.notes, el.created_at FROM execution_logs el
JOIN plan_tasks pt ON el.plan_task_id = pt.id
WHERE pt.daily_plan_id = $1
ORDER BY pt.position ASC
`

func (q *Queries) GetExecutionLogsByDailyPlan(ctx context.Context, dailyPlanID pgtype.UUID) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, getExecutionLogsByDailyPlan, dailyPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.PlanTaskID,
			&i.UserID,
			&i.Completed,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionLogsByUser = `-- name: GetExecutionLogsByUser :many
SELECT id, plan_task_id, user_id, completed, completed_at, notes, created_at FROM execution_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetExecutionLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetExecutionLogsByUser(ctx context.Context, arg GetExecutionLogsByUserParams) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, getExecutionLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.PlanTaskID,
			&i.UserID,
			&i.Completed,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInactiveUsers = `-- name: GetInactiveUsers :many
SELECT u.id, u.email, u.name FROM users u
JOIN behavior_profiles bp ON u.id = bp.user_id
WHERE bp.onboarding_completed = TRUE
  AND u.email_verified = TRUE
  AND (bp.last_notified_at IS NULL OR bp.last_notified_at::date < CURRENT_DATE)
  AND NOT EXISTS (
    SELECT 1 FROM daily_plans dp
    WHERE dp.user_id = u.id AND dp.plan_date >= CURRENT_DATE - INTERVAL '2 days'
  )
`

type GetInactiveUsersRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) GetInactiveUsers(ctx context.Context) ([]GetInactiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getInactiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInactiveUsersRow{}
	for rows.Next() {
		var i GetInactiveUsersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanTaskByID = `-- name: GetPlanTaskByID :one
SELECT id, daily_plan_id, title, description, category, difficulty, position, created_at, task_type, suggested_time, anchor_label FROM plan_tasks WHERE id = $1
`

func (q *Queries) GetPlanTaskByID(ctx context.Context, id pgtype.UUID) (PlanTask, error) {
	row := q.db.QueryRow(ctx, getPlanTaskByID, id)
	var i PlanTask
	err := row.Scan(
		&i.ID,
		&i.DailyPlanID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.Position,
		&i.CreatedAt,
		&i.TaskType,
		&i.SuggestedTime,
		&i.AnchorLabel,
	)
	return i, err
}

const getPlanTasksByDailyPlan = `-- name: GetPlanTasksByDailyPlan :many
SELECT id, daily_plan_id, title, description, category, difficulty, position, created_at, task_type, suggested_time, anchor_label FROM plan_tasks
WHERE daily_plan_id = $1
ORDER BY position ASC
`

func (q *Queries) GetPlanTasksByDailyPlan(ctx context.Context, dailyPlanID pgtype.UUID) ([]PlanTask, error) {
	rows, err := q.db.Query(ctx, getPlanTasksByDailyPlan, dailyPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanTask{}
	for rows.Next() {
		var i PlanTask
		if err := rows.Scan(
			&i.ID,
			&i.DailyPlanID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Difficulty,
			&i.Position,
			&i.CreatedAt,
			&i.TaskType,
			&i.SuggestedTime,
			&i.AnchorLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDailyPlans = `-- name: GetRecentDailyPlans :many
SELECT id, user_id, plan_date, difficulty_score, status, created_at, updated_at, prompt_version FROM daily_plans
WHERE user_id = $1
ORDER BY plan_date DESC
LIMIT $2
`

type GetRecentDailyPlansParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetRecentDailyPlans(ctx context.Context, arg GetRecentDailyPlansParams) ([]DailyPlan, error) {
	rows, err := q.db.Query(ctx, getRecentDailyPlans, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyPlan{}
	for rows.Next() {
		var i DailyPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanDate,
			&i.DifficultyScore,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PromptVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelapsingUsers = `-- name: GetRelapsingUsers :many
SELECT u.id, u.email, u.name, ast.completion_rate, ast.streak_count,
       bp.difficulty_level
FROM users u
JOIN behavior_profiles bp ON u.id = bp.user_id
JOIN adherence_states ast ON u.id = ast.user_id
WHERE bp.onboarding_completed = TRUE
  AND ast.completion_rate < 0.3
  AND ast.total_tasks > 0
  AND ast.last_computed_at::date = CURRENT_DATE
  AND (bp.last_notified_at IS NULL OR bp.last_notified_at::date < CURRENT_DATE)
`

type GetRelapsingUsersRow struct {
	ID              pgtype.UUID    `json:"id"`
	Email           string         `json:"email"`
	Name            string         `json:"name"`
	CompletionRate  pgtype.Numeric `json:"completion_rate"`
	StreakCount     int32          `json:"streak_count"`
	DifficultyLevel pgtype.Numeric `json:"difficulty_level"`
}

func (q *Queries) GetRelapsingUsers(ctx context.Context) ([]GetRelapsingUsersRow, error) {
	rows, err := q.db.Query(ctx, getRelapsingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRelapsingUsersRow{}
	for rows.Next() {
		var i GetRelapsingUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CompletionRate,
			&i.StreakCount,
			&i.DifficultyLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersNeedingReminder = `-- name: GetUsersNeedingReminder :many
SELECT u.id, u.email, u.name FROM users u
JOIN behavior_profiles bp ON u.id = bp.user_id
JOIN daily_plans dp ON u.id = dp.user_id
  AND dp.plan_date = CURRENT_DATE AND dp.status != 'expired'
LEFT JOIN execution_logs el ON el.user_id = u.id
  AND el.plan_task_id IN (SELECT pt.id FROM plan_tasks pt WHERE pt.daily_plan_id = dp.id)
  AND el.completed = TRUE
WHERE u.email_verified = TRUE
  AND bp.onboarding_completed = TRUE
  AND (bp.last_notified_at IS NULL OR bp.last_notified_at::date < CURRENT_DATE)
GROUP BY u.id, u.email, u.name
HAVING COUNT(el.id) = 0
`

type GetUsersNeedingReminderRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) GetUsersNeedingReminder(ctx context.Context) ([]GetUsersNeedingReminderRow, error) {
	rows, err := q.db.Query(ctx, getUsersNeedingReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersNeedingReminderRow{}
	for rows.Next() {
		var i GetUsersNeedingReminderRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithTodayAdherence = `-- name: GetUsersWithTodayAdherence :many
SELECT ast.user_id
FROM adherence_states ast
JOIN behavior_profiles bp ON ast.user_id = bp.user_id
WHERE ast.last_computed_at::date = CURRENT_DATE
  AND bp.onboarding_completed = TRUE
  AND ast.total_tasks > 0
`

func (q *Queries) GetUsersWithTodayAdherence(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUsersWithTodayAdherence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyCompletionTrends = `-- name: GetWeeklyCompletionTrends :many
SELECT date_trunc('week', dp.plan_date)::date AS week_start,
       COUNT(DISTINCT dp.id)::int AS plan_count,
       COUNT(pt.id)::int AS total_tasks,
       COUNT(el.id) FILTER (WHERE el.completed = TRUE)::int AS completed_tasks
FROM daily_plans dp
JOIN plan_tasks pt ON pt.daily_plan_id = dp.id
LEFT JOIN execution_logs el ON el.plan_task_id = pt.id AND el.completed = TRUE
WHERE dp.user_id = $1 AND dp.plan_date >= CURRENT_DATE - INTERVAL '28 days'
GROUP BY week_start
ORDER BY week_start
`

type GetWeeklyCompletionTrendsRow struct {
	WeekStart      pgtype.Date `json:"week_start"`
	PlanCount      int32       `json:"plan_count"`
	TotalTasks     int32       `json:"total_tasks"`
	CompletedTasks int32       `json:"completed_tasks"`
}

func (q *Queries) GetWeeklyCompletionTrends(ctx context.Context, userID pgtype.UUID) ([]GetWeeklyCompletionTrendsRow, error) {
	rows, err := q.db.Query(ctx, getWeeklyCompletionTrends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeeklyCompletionTrendsRow{}
	for rows.Next() {
		var i GetWeeklyCompletionTrendsRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.PlanCount,
			&i.TotalTasks,
			&i.CompletedTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBehaviorProfile = `-- name: UpdateBehaviorProfile :one
UPDATE behavior_profiles
SET goals = COALESCE($1, goals),
    constraints = COALESCE($2, constraints),
    psychological_state = COALESCE($3, psychological_state),
    difficulty_level = COALESCE($4, difficulty_level),
    onboarding_completed = COALESCE($5, onboarding_completed),
    delivery_mode = COALESCE($6, delivery_mode),
    emotional_state = COALESCE($7, emotional_state),
    ai_profile_summary = COALESCE($8, ai_profile_summary)
WHERE user_id = $9
RETURNING id, user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed, created_at, updated_at, last_notified_at, delivery_mode, emotional_state, ai_profile_summary
`

type UpdateBehaviorProfileParams struct {
	Goals               []byte         `json:"goals"`
	Constraints         []byte         `json:"constraints"`
	PsychologicalState  []byte         `json:"psychological_state"`
	DifficultyLevel     pgtype.Numeric `json:"difficulty_level"`
	OnboardingCompleted pgtype.Bool    `json:"onboarding_completed"`
	DeliveryMode        pgtype.Text    `json:"delivery_mode"`
	EmotionalState      pgtype.Text    `json:"emotional_state"`
	AiProfileSummary    []byte         `json:"ai_profile_summary"`
	UserID              pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateBehaviorProfile(ctx context.Context, arg UpdateBehaviorProfileParams) (BehaviorProfile, error) {
	row := q.db.QueryRow(ctx, updateBehaviorProfile,
		arg.Goals,
		arg.Constraints,
		arg.PsychologicalState,
		arg.DifficultyLevel,
		arg.OnboardingCompleted,
		arg.DeliveryMode,
		arg.EmotionalState,
		arg.AiProfileSummary,
		arg.UserID,
	)
	var i BehaviorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goals,
		&i.Constraints,
		&i.PsychologicalState,
		&i.DifficultyLevel,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastNotifiedAt,
		&i.DeliveryMode,
		&i.EmotionalState,
		&i.AiProfileSummary,
	)
	return i, err
}

const updateDailyPlanStatus = `-- name: UpdateDailyPlanStatus :one
UPDATE daily_plans SET status = $2 WHERE id = $1
RETURNING id, user_id, plan_date, difficulty_score, status, created_at, updated_at, prompt_version
`

type UpdateDailyPlanStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDailyPlanStatus(ctx context.Context, arg UpdateDailyPlanStatusParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, updateDailyPlanStatus, arg.ID, arg.Status)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptVersion,
	)
	return i, err
}

const updateProfileNotifiedAt = `-- name: UpdateProfileNotifiedAt :exec
UPDATE behavior_profiles SET last_notified_at = NOW() WHERE user_id = $1
`

func (q *Queries) UpdateProfileNotifiedAt(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateProfileNotifiedAt, userID)
	return err
}

const upsertAdherenceState = `-- name: UpsertAdherenceState :one

INSERT INTO adherence_states (user_id, completion_rate, streak_count, total_tasks, completed_tasks, difficulty_mismatch, last_computed_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (user_id) DO UPDATE
SET completion_rate = EXCLUDED.completion_rate,
    streak_count = EXCLUDED.streak_count,
    total_tasks = EXCLUDED.total_tasks,
    completed_tasks = EXCLUDED.completed_tasks,
    difficulty_mismatch = EXCLUDED.difficulty_mismatch,
    last_computed_at = NOW()
RETURNING id, user_id, completion_rate, streak_count, total_tasks, completed_tasks, difficulty_mismatch, last_computed_at, created_at, updated_at
`

type UpsertAdherenceStateParams struct {
	UserID             pgtype.UUID    `json:"user_id"`
	CompletionRate     pgtype.Numeric `json:"completion_rate"`
	StreakCount        int32          `json:"streak_count"`
	TotalTasks         int32          `json:"total_tasks"`
	CompletedTasks     int32          `json:"completed_tasks"`
	DifficultyMismatch bool           `json:"difficulty_mismatch"`
}

// Adherence States
func (q *Queries) UpsertAdherenceState(ctx context.Context, arg UpsertAdherenceStateParams) (AdherenceState, error) {
	row := q.db.QueryRow(ctx, upsertAdherenceState,
		arg.UserID,
		arg.CompletionRate,
		arg.StreakCount,
		arg.TotalTasks,
		arg.CompletedTasks,
		arg.DifficultyMismatch,
	)
	var i AdherenceState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompletionRate,
		&i.StreakCount,
		&i.TotalTasks,
		&i.CompletedTasks,
		&i.DifficultyMismatch,
		&i.LastComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExecutionLog = `-- name: UpsertExecutionLog :one

INSERT INTO execution_logs (plan_task_id, user_id, completed, completed_at, notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (plan_task_id) DO UPDATE
SET completed = EXCLUDED.completed,
    completed_at = EXCLUDED.completed_at,
    notes = EXCLUDED.notes
RETURNING id, plan_task_id, user_id, completed, completed_at, notes, created_at
`

type UpsertExecutionLogParams struct {
	PlanTaskID  pgtype.UUID        `json:"plan_task_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Notes       string             `json:"notes"`
}

// Execution Logs
func (q *Queries) UpsertExecutionLog(ctx context.Context, arg UpsertExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, upsertExecutionLog,
		arg.PlanTaskID,
		arg.UserID,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.PlanTaskID,
		&i.UserID,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
