// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: behavior.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdaptationLog = `-- name: CreateAdaptationLog :one

INSERT INTO adaptation_logs (user_id, adaptation_reason, difficulty_change, previous_difficulty, new_difficulty, trigger_metrics)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, adaptation_reason, difficulty_change, previous_difficulty, new_difficulty, trigger_metrics, created_at
`

type CreateAdaptationLogParams struct {
	UserID             pgtype.UUID    `json:"user_id"`
	AdaptationReason   string         `json:"adaptation_reason"`
	DifficultyChange   pgtype.Numeric `json:"difficulty_change"`
	PreviousDifficulty pgtype.Numeric `json:"previous_difficulty"`
	NewDifficulty      pgtype.Numeric `json:"new_difficulty"`
	TriggerMetrics     []byte         `json:"trigger_metrics"`
}

// Adaptation Logs
func (q *Queries) CreateAdaptationLog(ctx context.Context, arg CreateAdaptationLogParams) (AdaptationLog, error) {
	row := q.db.QueryRow(ctx, createAdaptationLog,
		arg.UserID,
		arg.AdaptationReason,
		arg.DifficultyChange,
		arg.PreviousDifficulty,
		arg.NewDifficulty,
		arg.TriggerMetrics,
	)
	var i AdaptationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdaptationReason,
		&i.DifficultyChange,
		&i.PreviousDifficulty,
		&i.NewDifficulty,
		&i.TriggerMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const createBehaviorProfile = `-- name: CreateBehaviorProfile :one

INSERT INTO behavior_profiles (user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed, created_at, updated_at
`

type CreateBehaviorProfileParams struct {
	UserID              pgtype.UUID    `json:"user_id"`
	Goals               []byte         `json:"goals"`
	Constraints         []byte         `json:"constraints"`
	PsychologicalState  []byte         `json:"psychological_state"`
	DifficultyLevel     pgtype.Numeric `json:"difficulty_level"`
	OnboardingCompleted bool           `json:"onboarding_completed"`
}

// Behavior Profiles
func (q *Queries) CreateBehaviorProfile(ctx context.Context, arg CreateBehaviorProfileParams) (BehaviorProfile, error) {
	row := q.db.QueryRow(ctx, createBehaviorProfile,
		arg.UserID,
		arg.Goals,
		arg.Constraints,
		arg.PsychologicalState,
		arg.DifficultyLevel,
		arg.OnboardingCompleted,
	)
	var i BehaviorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goals,
		&i.Constraints,
		&i.PsychologicalState,
		&i.DifficultyLevel,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDailyPlan = `-- name: CreateDailyPlan :one

INSERT INTO daily_plans (user_id, plan_date, difficulty_score, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, plan_date, difficulty_score, status, created_at, updated_at
`

type CreateDailyPlanParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	PlanDate        pgtype.Date    `json:"plan_date"`
	DifficultyScore pgtype.Numeric `json:"difficulty_score"`
	Status          string         `json:"status"`
}

// Daily Plans
func (q *Queries) CreateDailyPlan(ctx context.Context, arg CreateDailyPlanParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, createDailyPlan,
		arg.UserID,
		arg.PlanDate,
		arg.DifficultyScore,
		arg.Status,
	)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlanTask = `-- name: CreatePlanTask :one

INSERT INTO plan_tasks (daily_plan_id, title, description, category, difficulty, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, daily_plan_id, title, description, category, difficulty, position, created_at
`

type CreatePlanTaskParams struct {
	DailyPlanID pgtype.UUID    `json:"daily_plan_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Category    string         `json:"category"`
	Difficulty  pgtype.Numeric `json:"difficulty"`
	Position    int32          `json:"position"`
}

// Plan Tasks
func (q *Queries) CreatePlanTask(ctx context.Context, arg CreatePlanTaskParams) (PlanTask, error) {
	row := q.db.QueryRow(ctx, createPlanTask,
		arg.DailyPlanID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Difficulty,
		arg.Position,
	)
	var i PlanTask
	err := row.Scan(
		&i.ID,
		&i.DailyPlanID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBehaviorProfile = `-- name: DeleteBehaviorProfile :exec
DELETE FROM behavior_profiles WHERE user_id = $1
`

func (q *Queries) DeleteBehaviorProfile(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBehaviorProfile, userID)
	return err
}

const getActiveDailyPlan = `-- name: GetActiveDailyPlan :one
SELECT id, user_id, plan_date, difficulty_score, status, created_at, updated_at FROM daily_plans
WHERE user_id = $1 AND plan_date = CURRENT_DATE AND status != 'expired'
`

func (q *Queries) GetActiveDailyPlan(ctx context.Context, userID pgtype.UUID) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, getActiveDailyPlan, userID)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdaptationLogsByUser = `-- name: GetAdaptationLogsByUser :many
SELECT id, user_id, adaptation_reason, difficulty_change, previous_difficulty, new_difficulty, trigger_metrics, created_at FROM adaptation_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetAdaptationLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetAdaptationLogsByUser(ctx context.Context, arg GetAdaptationLogsByUserParams) ([]AdaptationLog, error) {
	rows, err := q.db.Query(ctx, getAdaptationLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdaptationLog{}
	for rows.Next() {
		var i AdaptationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AdaptationReason,
			&i.DifficultyChange,
			&i.PreviousDifficulty,
			&i.NewDifficulty,
			&i.TriggerMetrics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdherenceStateByUserID = `-- name: GetAdherenceStateByUserID :one
SELECT id, user_id, completion_rate, streak_count, total_tasks, completed_tasks, difficulty_mismatch, last_computed_at, created_at, updated_at FROM adherence_states WHERE user_id = $1
`

func (q *Queries) GetAdherenceStateByUserID(ctx context.Context, userID pgtype.UUID) (AdherenceState, error) {
	row := q.db.QueryRow(ctx, getAdherenceStateByUserID, userID)
	var i AdherenceState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompletionRate,
		&i.StreakCount,
		&i.TotalTasks,
		&i.CompletedTasks,
		&i.DifficultyMismatch,
		&i.LastComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBehaviorProfileByUserID = `-- name: GetBehaviorProfileByUserID :one
SELECT id, user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed, created_at, updated_at FROM behavior_profiles WHERE user_id = $1
`

func (q *Queries) GetBehaviorProfileByUserID(ctx context.Context, userID pgtype.UUID) (BehaviorProfile, error) {
	row := q.db.QueryRow(ctx, getBehaviorProfileByUserID, userID)
	var i BehaviorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goals,
		&i.Constraints,
		&i.PsychologicalState,
		&i.DifficultyLevel,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyPlanByUserAndDate = `-- name: GetDailyPlanByUserAndDate :one
SELECT id, user_id, plan_date, difficulty_score, status, created_at, updated_at FROM daily_plans WHERE user_id = $1 AND plan_date = $2
`

type GetDailyPlanByUserAndDateParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PlanDate pgtype.Date `json:"plan_date"`
}

func (q *Queries) GetDailyPlanByUserAndDate(ctx context.Context, arg GetDailyPlanByUserAndDateParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, getDailyPlanByUserAndDate, arg.UserID, arg.PlanDate)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionLogsByDailyPlan = `-- name: GetExecutionLogsByDailyPlan :many
SELECT el.id, el.plan_task_id, el.user_id, el.completed, el.completed_at, el.notes, el.created_at FROM execution_logs el
JOIN plan_tasks pt ON el.plan_task_id = pt.id
WHERE pt.daily_plan_id = $1
ORDER BY pt.position ASC
`

func (q *Queries) GetExecutionLogsByDailyPlan(ctx context.Context, dailyPlanID pgtype.UUID) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, getExecutionLogsByDailyPlan, dailyPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.PlanTaskID,
			&i.UserID,
			&i.Completed,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionLogsByUser = `-- name: GetExecutionLogsByUser :many
SELECT id, plan_task_id, user_id, completed, completed_at, notes, created_at FROM execution_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetExecutionLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetExecutionLogsByUser(ctx context.Context, arg GetExecutionLogsByUserParams) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, getExecutionLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.PlanTaskID,
			&i.UserID,
			&i.Completed,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanTaskByID = `-- name: GetPlanTaskByID :one
SELECT id, daily_plan_id, title, description, category, difficulty, position, created_at FROM plan_tasks WHERE id = $1
`

func (q *Queries) GetPlanTaskByID(ctx context.Context, id pgtype.UUID) (PlanTask, error) {
	row := q.db.QueryRow(ctx, getPlanTaskByID, id)
	var i PlanTask
	err := row.Scan(
		&i.ID,
		&i.DailyPlanID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanTasksByDailyPlan = `-- name: GetPlanTasksByDailyPlan :many
SELECT id, daily_plan_id, title, description, category, difficulty, position, created_at FROM plan_tasks
WHERE daily_plan_id = $1
ORDER BY position ASC
`

func (q *Queries) GetPlanTasksByDailyPlan(ctx context.Context, dailyPlanID pgtype.UUID) ([]PlanTask, error) {
	rows, err := q.db.Query(ctx, getPlanTasksByDailyPlan, dailyPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanTask{}
	for rows.Next() {
		var i PlanTask
		if err := rows.Scan(
			&i.ID,
			&i.DailyPlanID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Difficulty,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDailyPlans = `-- name: GetRecentDailyPlans :many
SELECT id, user_id, plan_date, difficulty_score, status, created_at, updated_at FROM daily_plans
WHERE user_id = $1
ORDER BY plan_date DESC
LIMIT $2
`

type GetRecentDailyPlansParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetRecentDailyPlans(ctx context.Context, arg GetRecentDailyPlansParams) ([]DailyPlan, error) {
	rows, err := q.db.Query(ctx, getRecentDailyPlans, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyPlan{}
	for rows.Next() {
		var i DailyPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanDate,
			&i.DifficultyScore,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBehaviorProfile = `-- name: UpdateBehaviorProfile :one
UPDATE behavior_profiles
SET goals = COALESCE($1, goals),
    constraints = COALESCE($2, constraints),
    psychological_state = COALESCE($3, psychological_state),
    difficulty_level = COALESCE($4, difficulty_level),
    onboarding_completed = COALESCE($5, onboarding_completed)
WHERE user_id = $6
RETURNING id, user_id, goals, constraints, psychological_state, difficulty_level, onboarding_completed, created_at, updated_at
`

type UpdateBehaviorProfileParams struct {
	Goals               []byte         `json:"goals"`
	Constraints         []byte         `json:"constraints"`
	PsychologicalState  []byte         `json:"psychological_state"`
	DifficultyLevel     pgtype.Numeric `json:"difficulty_level"`
	OnboardingCompleted pgtype.Bool    `json:"onboarding_completed"`
	UserID              pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateBehaviorProfile(ctx context.Context, arg UpdateBehaviorProfileParams) (BehaviorProfile, error) {
	row := q.db.QueryRow(ctx, updateBehaviorProfile,
		arg.Goals,
		arg.Constraints,
		arg.PsychologicalState,
		arg.DifficultyLevel,
		arg.OnboardingCompleted,
		arg.UserID,
	)
	var i BehaviorProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goals,
		&i.Constraints,
		&i.PsychologicalState,
		&i.DifficultyLevel,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDailyPlanStatus = `-- name: UpdateDailyPlanStatus :one
UPDATE daily_plans SET status = $2 WHERE id = $1
RETURNING id, user_id, plan_date, difficulty_score, status, created_at, updated_at
`

type UpdateDailyPlanStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDailyPlanStatus(ctx context.Context, arg UpdateDailyPlanStatusParams) (DailyPlan, error) {
	row := q.db.QueryRow(ctx, updateDailyPlanStatus, arg.ID, arg.Status)
	var i DailyPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.DifficultyScore,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdherenceState = `-- name: UpsertAdherenceState :one

INSERT INTO adherence_states (user_id, completion_rate, streak_count, total_tasks, completed_tasks, difficulty_mismatch, last_computed_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (user_id) DO UPDATE
SET completion_rate = EXCLUDED.completion_rate,
    streak_count = EXCLUDED.streak_count,
    total_tasks = EXCLUDED.total_tasks,
    completed_tasks = EXCLUDED.completed_tasks,
    difficulty_mismatch = EXCLUDED.difficulty_mismatch,
    last_computed_at = NOW()
RETURNING id, user_id, completion_rate, streak_count, total_tasks, completed_tasks, difficulty_mismatch, last_computed_at, created_at, updated_at
`

type UpsertAdherenceStateParams struct {
	UserID             pgtype.UUID    `json:"user_id"`
	CompletionRate     pgtype.Numeric `json:"completion_rate"`
	StreakCount        int32          `json:"streak_count"`
	TotalTasks         int32          `json:"total_tasks"`
	CompletedTasks     int32          `json:"completed_tasks"`
	DifficultyMismatch bool           `json:"difficulty_mismatch"`
}

// Adherence States
func (q *Queries) UpsertAdherenceState(ctx context.Context, arg UpsertAdherenceStateParams) (AdherenceState, error) {
	row := q.db.QueryRow(ctx, upsertAdherenceState,
		arg.UserID,
		arg.CompletionRate,
		arg.StreakCount,
		arg.TotalTasks,
		arg.CompletedTasks,
		arg.DifficultyMismatch,
	)
	var i AdherenceState
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompletionRate,
		&i.StreakCount,
		&i.TotalTasks,
		&i.CompletedTasks,
		&i.DifficultyMismatch,
		&i.LastComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExecutionLog = `-- name: UpsertExecutionLog :one

INSERT INTO execution_logs (plan_task_id, user_id, completed, completed_at, notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (plan_task_id) DO UPDATE
SET completed = EXCLUDED.completed,
    completed_at = EXCLUDED.completed_at,
    notes = EXCLUDED.notes
RETURNING id, plan_task_id, user_id, completed, completed_at, notes, created_at
`

type UpsertExecutionLogParams struct {
	PlanTaskID  pgtype.UUID        `json:"plan_task_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Notes       string             `json:"notes"`
}

// Execution Logs
func (q *Queries) UpsertExecutionLog(ctx context.Context, arg UpsertExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, upsertExecutionLog,
		arg.PlanTaskID,
		arg.UserID,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.PlanTaskID,
		&i.UserID,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
