// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one

INSERT INTO chat_messages (user_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, content, created_at
`

type CreateChatMessageParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Role    string      `json:"role"`
	Content string      `json:"content"`
}

// Chat Messages
func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage, arg.UserID, arg.Role, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChatHistory = `-- name: DeleteChatHistory :exec
DELETE FROM chat_messages WHERE user_id = $1
`

func (q *Queries) DeleteChatHistory(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatHistory, userID)
	return err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, user_id, role, content, created_at FROM chat_messages
WHERE user_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListChatMessagesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
