// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJournalEntriesByUser = `-- name: GetJournalEntriesByUser :many
SELECT id, user_id, content, mood_score, prompt_used, entry_date, created_at, updated_at FROM journal_entries
WHERE user_id = $1
ORDER BY entry_date DESC
LIMIT $2 OFFSET $3
`

type GetJournalEntriesByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetJournalEntriesByUser(ctx context.Context, arg GetJournalEntriesByUserParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, getJournalEntriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.MoodScore,
			&i.PromptUsed,
			&i.EntryDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalEntryByDate = `-- name: GetJournalEntryByDate :one
SELECT id, user_id, content, mood_score, prompt_used, entry_date, created_at, updated_at FROM journal_entries
WHERE user_id = $1 AND entry_date = $2
`

type GetJournalEntryByDateParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EntryDate pgtype.Date `json:"entry_date"`
}

func (q *Queries) GetJournalEntryByDate(ctx context.Context, arg GetJournalEntryByDateParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByDate, arg.UserID, arg.EntryDate)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.MoodScore,
		&i.PromptUsed,
		&i.EntryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentMoodScores = `-- name: GetRecentMoodScores :many
SELECT entry_date, mood_score FROM journal_entries
WHERE user_id = $1
ORDER BY entry_date DESC
LIMIT $2
`

type GetRecentMoodScoresParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type GetRecentMoodScoresRow struct {
	EntryDate pgtype.Date `json:"entry_date"`
	MoodScore int32       `json:"mood_score"`
}

func (q *Queries) GetRecentMoodScores(ctx context.Context, arg GetRecentMoodScoresParams) ([]GetRecentMoodScoresRow, error) {
	rows, err := q.db.Query(ctx, getRecentMoodScores, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentMoodScoresRow{}
	for rows.Next() {
		var i GetRecentMoodScoresRow
		if err := rows.Scan(&i.EntryDate, &i.MoodScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJournalEntry = `-- name: UpsertJournalEntry :one

INSERT INTO journal_entries (user_id, content, mood_score, prompt_used, entry_date)
VALUES ($1, $2, $3, $4, CURRENT_DATE)
ON CONFLICT (user_id, entry_date) DO UPDATE
SET content = EXCLUDED.content,
    mood_score = EXCLUDED.mood_score,
    prompt_used = EXCLUDED.prompt_used
RETURNING id, user_id, content, mood_score, prompt_used, entry_date, created_at, updated_at
`

type UpsertJournalEntryParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Content    string      `json:"content"`
	MoodScore  int32       `json:"mood_score"`
	PromptUsed string      `json:"prompt_used"`
}

// Journal Entries
func (q *Queries) UpsertJournalEntry(ctx context.Context, arg UpsertJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, upsertJournalEntry,
		arg.UserID,
		arg.Content,
		arg.MoodScore,
		arg.PromptUsed,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.MoodScore,
		&i.PromptUsed,
		&i.EntryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
